name: clang-format Check

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'examples'
          - 'converter'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.8.0
      with:
        exclude-regex: 'src/interfaces/predicates.*'
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
        fallback-style: 'Google'